name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  apply:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.environment || 'dev' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: environments/${{ env.ENV }}
        run: terraform init

      - name: Terraform Apply
        working-directory: environments/${{ env.ENV }}
        run: terraform apply -var-file=${{ env.ENV }}.tfvars -auto-approve
